# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import weather_pb2 as weather__pb2


class WeatherStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/Weather/subscribe',
                request_serializer=weather__pb2.CountryRequest.SerializeToString,
                response_deserializer=weather__pb2.ForecastResponse.FromString,
                )


class WeatherServicer(object):
    """Missing associated documentation comment in .proto file"""

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=weather__pb2.CountryRequest.FromString,
                    response_serializer=weather__pb2.ForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Weather', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Weather(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Weather/subscribe',
            weather__pb2.CountryRequest.SerializeToString,
            weather__pb2.ForecastResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
