# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rweather.proto\"%\n\x0e\x43ountryRequest\x12\x13\n\x0b\x63ountryName\x18\x01 \x01(\t\"P\n\x10\x46orecastResponse\x12\x13\n\x04time\x18\x01 \x01(\x0b\x32\x05.Time\x12\'\n\x0eregionForecast\x18\x02 \x03(\x0b\x32\x0f.RegionForecast\"_\n\x04Time\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\x0c\n\x04hour\x18\x04 \x01(\x05\x12\x0e\n\x06minute\x18\x05 \x01(\x05\x12\x0f\n\x07seconds\x18\x06 \x01(\x05\"\xea\x01\n\x0eRegionForecast\x12\x12\n\nregionName\x18\x01 \x01(\t\x12.\n\ncloudiness\x18\x02 \x01(\x0e\x32\x1a.RegionForecast.Cloudiness\x12\x0c\n\x04temp\x18\x03 \x01(\x01\x12$\n\x05scale\x18\x04 \x01(\x0e\x32\x15.RegionForecast.Scale\".\n\nCloudiness\x12\t\n\x05SUNNY\x10\x00\x12\t\n\x05MIXED\x10\x01\x12\n\n\x06\x43LOUDY\x10\x02\"0\n\x05Scale\x12\x0b\n\x07\x43\x45LSIUS\x10\x00\x12\x0e\n\nFAHRENHEIT\x10\x01\x12\n\n\x06KELVIN\x10\x02\x32<\n\x07Weather\x12\x31\n\tsubscribe\x12\x0f.CountryRequest\x1a\x11.ForecastResponse0\x01\x62\x06proto3'
)



_REGIONFORECAST_CLOUDINESS = _descriptor.EnumDescriptor(
  name='Cloudiness',
  full_name='RegionForecast.Cloudiness',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUNNY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIXED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUDY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=374,
  serialized_end=420,
)
_sym_db.RegisterEnumDescriptor(_REGIONFORECAST_CLOUDINESS)

_REGIONFORECAST_SCALE = _descriptor.EnumDescriptor(
  name='Scale',
  full_name='RegionForecast.Scale',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CELSIUS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAHRENHEIT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KELVIN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=422,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_REGIONFORECAST_SCALE)


_COUNTRYREQUEST = _descriptor.Descriptor(
  name='CountryRequest',
  full_name='CountryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryName', full_name='CountryRequest.countryName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=54,
)


_FORECASTRESPONSE = _descriptor.Descriptor(
  name='ForecastResponse',
  full_name='ForecastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ForecastResponse.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regionForecast', full_name='ForecastResponse.regionForecast', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=136,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='Time.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='Time.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='Time.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hour', full_name='Time.hour', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minute', full_name='Time.minute', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='Time.seconds', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=233,
)


_REGIONFORECAST = _descriptor.Descriptor(
  name='RegionForecast',
  full_name='RegionForecast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regionName', full_name='RegionForecast.regionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudiness', full_name='RegionForecast.cloudiness', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='RegionForecast.temp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='RegionForecast.scale', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGIONFORECAST_CLOUDINESS,
    _REGIONFORECAST_SCALE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=470,
)

_FORECASTRESPONSE.fields_by_name['time'].message_type = _TIME
_FORECASTRESPONSE.fields_by_name['regionForecast'].message_type = _REGIONFORECAST
_REGIONFORECAST.fields_by_name['cloudiness'].enum_type = _REGIONFORECAST_CLOUDINESS
_REGIONFORECAST.fields_by_name['scale'].enum_type = _REGIONFORECAST_SCALE
_REGIONFORECAST_CLOUDINESS.containing_type = _REGIONFORECAST
_REGIONFORECAST_SCALE.containing_type = _REGIONFORECAST
DESCRIPTOR.message_types_by_name['CountryRequest'] = _COUNTRYREQUEST
DESCRIPTOR.message_types_by_name['ForecastResponse'] = _FORECASTRESPONSE
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['RegionForecast'] = _REGIONFORECAST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryRequest = _reflection.GeneratedProtocolMessageType('CountryRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYREQUEST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:CountryRequest)
  })
_sym_db.RegisterMessage(CountryRequest)

ForecastResponse = _reflection.GeneratedProtocolMessageType('ForecastResponse', (_message.Message,), {
  'DESCRIPTOR' : _FORECASTRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:ForecastResponse)
  })
_sym_db.RegisterMessage(ForecastResponse)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

RegionForecast = _reflection.GeneratedProtocolMessageType('RegionForecast', (_message.Message,), {
  'DESCRIPTOR' : _REGIONFORECAST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:RegionForecast)
  })
_sym_db.RegisterMessage(RegionForecast)



_WEATHER = _descriptor.ServiceDescriptor(
  name='Weather',
  full_name='Weather',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=472,
  serialized_end=532,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='Weather.subscribe',
    index=0,
    containing_service=None,
    input_type=_COUNTRYREQUEST,
    output_type=_FORECASTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHER)

DESCRIPTOR.services_by_name['Weather'] = _WEATHER

# @@protoc_insertion_point(module_scope)
